[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/kirvano-webhook"
  to = "/.netlify/functions/kirvano-webhook"
  status = 200

[build.environment]
  KIRVANO_TOKEN = "brincafacil01"