[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[edge_functions]]
  function = "kirvano-webhook"
  path = "/api/kirvano-webhook"

[build.environment]
  KIRVANO_TOKEN = "brincafacil01"

[[edge_functions]]
function = "hello"
path = "/test"